# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='club_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='club_nights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('night_name', models.CharField(max_length=128)),
                ('night_day', models.DateField()),
                ('club_rating', models.IntegerField()),
                ('club_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcn.club_list')),
            ],
        ),
    ]
