# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcn', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='club_list',
            new_name='Club',
        ),
        migrations.RenameModel(
            old_name='club_nights',
            new_name='Night',
        ),
        migrations.RenameField(
            model_name='night',
            old_name='club_list',
            new_name='club_name',
        ),
    ]
