# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcn', '0002_auto_20180308_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='night',
            old_name='club_name',
            new_name='club_list',
        ),
    ]
