# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcn', '0003_auto_20180308_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='night',
            name='club_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='night',
            name='night_day',
            field=models.CharField(max_length=128),
        ),
    ]
