# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcn', '0007_auto_20180315_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('night_name', models.CharField(max_length=128)),
                ('night_day', models.CharField(max_length=128)),
                ('club_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcn.Club')),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_rating', models.IntegerField(default=0)),
            ],
        ),
    ]
