# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcn', '0009_auto_20180320_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='night',
            name='club_list',
            field=models.CharField(max_length=128),
        ),
    ]
