# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcn', '0019_auto_20180321_1123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserReview',
            new_name='UserReviewForm',
        ),
        migrations.AlterField(
            model_name='night',
            name='club_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcn.Club'),
        ),
    ]
