# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcn', '0020_auto_20180321_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreviewform',
            name='name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='gcn.Club'),
            preserve_default=False,
        ),
    ]
