# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcn', '0023_auto_20180321_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreviewform',
            name='club_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
