# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcn', '0026_auto_20180321_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreviewform',
            old_name='club_list',
            new_name='club_name_list',
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='night',
            name='club_list',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='userreviewform',
            name='club_rating',
            field=models.CharField(max_length=128),
        ),
    ]
