# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcn', '0028_auto_20180321_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_rating', models.IntegerField(default=0)),
                ('club_name_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcn.Club')),
            ],
        ),
        migrations.AlterField(
            model_name='userreviewform',
            name='club_rating',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
