# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcn', '0029_auto_20180322_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_rating',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='club_rating',
            field=models.BigIntegerField(default=0),
        ),
    ]
