# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcn', '0030_auto_20180322_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreviewform',
            name='club_rating',
            field=models.BigIntegerField(default=0),
        ),
    ]
