# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcn', '0031_auto_20180322_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreview',
            old_name='club_name_list',
            new_name='club_list',
        ),
        migrations.RenameField(
            model_name='userreviewform',
            old_name='club_name_list',
            new_name='club_list',
        ),
    ]
