# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcn', '0032_auto_20180322_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gcn.UserForm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreviewform',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gcn.UserForm'),
            preserve_default=False,
        ),
    ]
